import { Lato } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Common/header/Navbar";
import Footer from "@/components/Common/footer/Footer";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Plan Pixel",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lato.className} mx-auto max-w-screen-xl`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
